name: "Sample Workflow"
on: 
    push: 
        branches: 
        - main
        - master
jobs: 
    testing_job:
        runs-on: ubuntu-latest
        steps: 
            - name: "Welcome Step"
              run: |
                echo "Welcome to this step"
                ls -a

            - name: "Checkout from github directory"
              uses: actions/checkout@v4



    # build docker image

            - name: build docker image
              run: sudo docker build -t pratproject:latest .


    #login into docker hub
            - name: Login to Docker Hub
              run: |
                    sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}" 
                    sudo docker images 




    # pushing to docker hub

            - name: push to docker hub
              run: sudo docker push olaranmmy/pratproject:latest

             








         


